Updated french translation
newsboat/newsboat pull request #1981
Opened 2022-03-03 13:51 UTC by Tonus1

I reviewed a few strings and added a few missing.

2022-03-03 20:26 UTC, Minoru requested changes
Thank you for the pull request, and sorry I didn't respond to #1979 in time!

This looks quite nice, but there are a few messages that should've been updated when you removed the 'fuzzy" tag. I commented on the ones that I spotted, but I don't speak French so I could have missed some. Please re-read them all and make sure that the translation *really* matches the English original, including the capitalization and punctuation.

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +"Language-Team: French <kde-i18n-doc@kde.org>\n"
We don't have language teams in Newsboat, so we enumerate all the translators in this field. Please roll back this change, and add yourself.

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +"`%s' (y : Oui n : No)? "
The original string doesn't contain `%s`; are you sure the translation is correct?

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +msgstr "%s est déjà dans la file"
```suggestion
msgstr "%s est déjà dans la file."
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +msgstr "Echec d'analyse de la séquence d'opérations sur (%s)"
```suggestion
msgstr "Echec d'analyse de la séquence d'opérations sur %s"
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Erreur : échec d'analyse du fichier OPML %s"
```suggestion
msgstr "Erreur : échec d'analyse du fichier OPML \"%s\""
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +#, c-format
The translation ends with `%s`, whereas the original message doesn't; are you sure the translation is correct?

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
> +#, c-format
I can't mark the offending line, but "podboat" in the translated message should start with a capital letter.

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Echec d'ouverture du fichier (%s)"
```suggestion
msgstr "Echec d'ouverture du fichier: %s"
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Echec de lecture de ligne %u (%s)"
```suggestion
msgstr "Echec de lecture de ligne %u: %s"
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Erreur : Echec d'éxécution des commandes de démarrage"
```suggestion
msgstr "Erreur : echec d'éxécution des commandes de démarrage"
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Echec d'ouverture du fichier de verrouillage : '%s' (%s)"
Please check this translation; the punctuation at the end of the messages is different.

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  msgstr "Echec d'écriture du PID dans le fichier de verrouillage : '%s' (%s)"
Please check this translation, as the punctuation at the end differs between original and translation.

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  "newsboat : rechargement terminé, %f fils à lire (%n articles à lire au total)"
```suggestion
"Newsboat : rechargement terminé, %f fils à lire (%n articles à lire au total)"
```

2022-03-03 20:26 UTC, Minoru commented on po/fr.po
>  "'%F'&? - %U"
Please update the translation — note that the punctuation around `F` is different.

2022-03-04 01:05 UTC, Tonus1 commented
I'm quite new to pull requests and corrected all that in my file... I will try a new pull-request.
Sorry for the mess !

2022-03-04 01:05 UTC, closed without merging