Ability to display the search phrase in the title
newsboat/newsboat pull request #2055
Opened 2022-05-04 13:34 UTC by bogdasar1985

https://github.com/newsboat/newsboat/issues/2043

2022-05-04 13:57 UTC, bogdasar1985 commented
That is also should be documented.

2022-05-09 17:09 UTC, Minoru requested changes
Sorry for the slow response! I think the code could be made more maintainable by avoiding copying, see my comment below.

I also agree that this should be documented and added to the default `searchresult-title-format`. Please do that :)

2022-05-09 17:09 UTC, Minoru commented on src/searchresultslistformaction.cpp
> +	fmt.register_fmt('s', search_phrase);
Why copy the entire method? I think one could just call the base method and add to its result:

```c++
FmtStrFormatter fmt = ItemListFormAction::setup_head_formatter(…);
fmt.register_fmt('s', search_phrase);
return fmt;
```

2022-05-10 08:58 UTC, Minoru requested changes
The code looks good, now all that's left is to document this and change the default.

2022-05-11 17:40 UTC, Minoru commented on doc/newsboat.asciidoc
> +.Search Result Title Format Identifiers
I'd move this table up, right after the one for the article list, and added a note that all of the article list identifiers are supported here too.

2022-05-11 17:42 UTC, Minoru commented on doc/configcommands.dsv
> +searchresult-title-format||<format>||"%N %V - Search results:\"%s\" (%u unread, %t total)%?F? matching filter '%F'&?" (localized)||Format of the title in search result. See "Format Strings" section o
```suggestion
searchresult-title-format||<format>||"%N %V - Search results for '%s' (%u unread, %t total)%?F? matching filter '%F'&?" (localized)||Format of the title in search result. See "Format Strings" section of Newsboat manual for details on available formats.||searchresult-title-format "Search result"
```

I think this reads better, and the quotes are consistent with what we use for the filter.

2022-05-11 17:42 UTC, Minoru commented on doc/newsboat.asciidoc
> +Search Result:<<searchresult-title-format,+searchresult-title-format+>>:%N %V - Search results:\"%s\" (%u unread, %t total)%?F? matching filter `%F'&?
```suggestion
Search Result:<<searchresult-title-format,+searchresult-title-format+>>:%N %V - Search results for '%s' (%u unread, %t total)%?F? matching filter `%F'&?
```

2022-05-11 17:43 UTC, Minoru commented on src/configcontainer.cpp
> +		ConfigData(_("%N %V - Search results:\"%s\" (%u unread, %t total)%?F? matching filter '%F'&?"),
```suggestion
		ConfigData(_("%N %V - Search results for '%s' (%u unread, %t total)%?F? matching filter '%F'&?"),
```

2022-05-11 17:44 UTC, Minoru commented
Almost there! :)

2022-05-12 18:11 UTC, Minoru approved these changes
You forgot to add a note that `searchresult-title-format` supports the same identifiers as `articlelist-title-format`. When marking a review comment as resolved, please make sure it's *really* resolved ;)

Anyway, this looks excellent and I'm merging. Thanks for the work!

2022-05-12 18:14 UTC, bogdasar1985 commented
@Minoru Great! Please, check IRC channel. I suggested something there. I will open an issue if there is no answer.

2022-05-12 18:33 UTC, merged