Stop scrolling to top of article when window is resized
newsboat/newsboat pull request #2075
Opened 2022-05-26 15:34 UTC by dennisschagt

Fixes https://github.com/newsboat/newsboat/issues/2073
Fixes https://github.com/newsboat/newsboat/issues/1298

2022-05-26 15:45 UTC, dennisschagt commented
From https://github.com/newsboat/newsboat/issues/1298#issuecomment-731631997:
> Just resetting the position is an easy way out. Coming up with a more intelligent algorithm sounds like a pretty interesting problem, actually :)

There might be some intelligent algorithm possible, but implementing it doesn't sound interesting to me :)
For now, I just changed back to the old behavior of keeping the same scroll offset (same line number on top) when resizing the terminal.

2022-05-26 20:37 UTC, Minoru requested changes
Glad you're back Dennis :) The changes look good, but please add a test for new `TextView` behaviour; I worked on `ListWidget` recently, and it reminded me that it's better to get tests while the reasoning behind the code is still fresh in the mind.

2022-05-26 20:37 UTC, Minoru commented on src/textviewwidget.cpp
> +	}
Could you please add a test for this?

2022-05-26 22:20 UTC, dennisschagt commented on src/textviewwidget.cpp
> +	}
Sure, done

2022-05-27 20:32 UTC, Minoru requested changes

2022-05-27 20:32 UTC, Minoru commented on test/textviewwidget.cpp
> +	SECTION("scroll_page_up() moves up just enough such that there is a single line of overlap between old and niw view") {
```suggestion
	SECTION("scroll_page_up() moves up just enough such that there is a single line of overlap between old and new view") {
```

2022-05-27 20:32 UTC, Minoru commented on test/textviewwidget.cpp
> +	SECTION("scroll_page_down() moves down just enough such that there is a single line of overlap between old and niw view") {
```suggestion
	SECTION("scroll_page_down() moves down just enough such that there is a single line of overlap between old and new view") {
```

2022-05-28 11:46 UTC, dennisschagt commented on test/textviewwidget.cpp
> +	newsboat::View v(&c);
I just realized it is not even necessary at all.
The only place which activates the terminal/ncurses "application mode" is the `form.run(-3)` call.
So, just adding a single `Stfl::reset()` call directly after that works fine.

2022-05-28 12:45 UTC, Minoru approved these changes

2022-05-28 12:45 UTC, merged

2022-05-28 12:45 UTC, Minoru commented
Thank you!