Only autoenqueue podcasts with a valid or empty type
newsboat/newsboat pull request #2378
Opened 2023-03-16 20:33 UTC by dennisschagt

Fixes https://github.com/newsboat/newsboat/issues/2367

2023-03-16 20:47 UTC, der-lyse commented on src/queuemanager.cpp
> +				" becausoe of invalid podcast type `%s'", enclosure_url, enclosure_type);
```suggestion
				" because of invalid podcast type `%s'", enclosure_url, enclosure_type);
```

2023-03-16 20:48 UTC, dennisschagt commented on src/queuemanager.cpp
> +				" becausoe of invalid podcast type `%s'", enclosure_url, enclosure_type);
Oops, fixed

2023-03-26 17:47 UTC, Minoru requested changes
Sorry I'm so late with the review!

I agree with the new `if` condition, but I think it should be in `RssParser`. In #2218 individual parsers (RSS 1.0, Atom etc.) learned to extract *all* the enclosures, and `RssParser` was made responsible for picking the "best" enclosure. I think we should just to modify the algorithm there.

2023-04-02 18:56 UTC, dennisschagt commented
No problem, thank you for the review anyway!

> In https://github.com/newsboat/newsboat/pull/2218 individual parsers (RSS 1.0, Atom etc.) learned to extract all the enclosures, and RssParser was made responsible for picking the "best" enclosure. I think we should just to modify the algorithm there.

I prefer to keep the decision of which items to (auto-)enqueue in the queuemanager.
My idea for enclosures and other media attachments is as follows:
- Support multiple attachments (both enclosures and `media:content` elements, removing the need to pick the "best" enclosure)
- Enqueue only items with audio/video/unknown mime-type (specifically, don't enqueue images => check added in this PR)
- Show image attachments near the top of the itemview (between the headers and the actual text, rendering them similar to links specified in item's HTML content)
- Related idea: https://github.com/newsboat/newsboat/issues/2305#issuecomment-1493412650

To be able to show images, we should not already filter them out in the `RssParser`.

Does that make sense to you / do you agree?

2023-06-12 20:47 UTC, Minoru approved these changes
Yup, makes total sense! I failed to consider how we could evolve this.

2023-06-12 20:48 UTC, merged