Refactor: transform `std::vector<LinkPair>` to separate class `Links`
newsboat/newsboat pull request #2493
Opened 2023-07-15 10:58 UTC by bogdasar1985

Issue https://github.com/newsboat/newsboat/issues/2464

According to this commit https://github.com/newsboat/newsboat/commit/0684f78c9b3f01258d23153ce70b37b4eb76763c I can't use `make depslist` anymore, so I add file `src/links.cpp` into `mk/newsboat.deps` manually in alphabetical order.

2023-07-18 19:49 UTC, Minoru requested changes
Looks pretty good!

Can you please add tests for the two invariants mentioned in https://github.com/newsboat/newsboat/issues/2464?

2023-07-18 19:49 UTC, Minoru commented on include/links.h
> +// This enum has to be kept in sync with enum LinkType in rust/libnewsboat/src/htmlrenderer.rs
Please also move rust/libnewsboat/src/htmlrenderer.rs to links.rs, update a comment in it to point to links.h, and update rust/libnewsboat/src/mod.rs to replace `htmlrenderer` with `links`.

2023-07-18 19:49 UTC, Minoru commented on include/links.h
> +#define LINKS_H_
In Newsboat, we prefix all our include guards with `NEWSBOAT_`; please do that too.

2023-07-18 19:49 UTC, Minoru commented on src/htmlrenderer.cpp
> +unsigned int HtmlRenderer::add_link(Links& links,
Can we delete this method, and replace calls to it with `links.add_link(..)`?

2023-07-19 09:02 UTC, bogdasar1985 commented
@Minoru I also wanna change `std::pair` to structure as you mentioned, because things like this `links.begin()->first` looks terrible. And `std::pair` is more about locally in-place usage (for example, iterate over `std::map`) and it's not our case.

2023-07-20 18:10 UTC, Minoru approved these changes
Excellent, thank you very much!

2023-07-20 18:10 UTC, merged